kubevirt:
  installOperator: true 
  installCR: true
  image: registry.suse.com/suse/sles/15.5/virt-operator:0.58.0-150500.4.21
  pullPolicy: IfNotPresent

cdi:
  installOperator: false
  installCR: false
  version: 1.55.0-150500.3.18
  operatorImage: registry.suse.com/suse/sles/15.5/cdi-operator:1.55.0-150500.3.18
  controllerImage: registry.suse.com/suse/sles/15.5/cdi-controller:1.55.0-150500.3.18
  importerImage: registry.suse.com/suse/sles/15.5/cdi-importer:1.55.0-150500.3.18
  clonerImage: registry.suse.com/suse/sles/15.5/cdi-cloner:1.55.0-150500.3.18
  apiserverImage: registry.suse.com/suse/sles/15.5/cdi-apiserver:1.55.0-150500.3.18
  uploadserverImage: registry.suse.com/suse/sles/15.5/cdi-uploadserver:1.55.0-150500.3.18
  uploadproxyImage: registry.suse.com/suse/sles/15.5/cdi-uploadproxy:1.55.0-150500.3.18
  pullPolicy: IfNotPresent



